#!/usr/bin/env python3
"""Regenerate the design-system wall inside index.html from what was captured.

Reads images/design-systems/*.jpg plus the full 138-name library list and
rewrites the block between the WALL markers. Run after tools/capture.sh.
"""
import os, re, html
from urllib.parse import urlparse

ALL = open('tools/library.txt').read().split()
URLS = {}
for line in open('tools/design-systems.tsv'):
    if '\t' in line:
        n, u = line.rstrip('\n').split('\t', 1)
        URLS[n] = urlparse(u).netloc.replace('www.', '')
shots = sorted(f[:-4] for f in os.listdir('images/design-systems') if f.endswith('.jpg'))
rest = [n for n in ALL if n not in shots]

def label(n):
    return n.replace('-', ' ')

rows = [shots[i::3] for i in range(3)]

def row_markup(items, idx):
    tiles = []
    for n in items:
        tiles.append(
            '          <figure class="tile">\n'
            '            <div class="tile__chrome">\n'
            '              <span class="tile__lights" aria-hidden="true"><i></i><i></i><i></i></span>\n'
            '              <span class="tile__bar"><span class="tile__host">%s</span></span>\n'
            '              <span class="tile__lights tile__lights--ghost" aria-hidden="true"></span>\n'
            '            </div>\n'
            '            <img src="/images/design-systems/%s.jpg" alt="The %s homepage" loading="lazy"\n'
            '              width="720" height="450">\n'
            '          </figure>' % (html.escape(URLS.get(n, label(n))), n, html.escape(label(n))))
    body = '\n'.join(tiles)
    # the track is duplicated so the loop is seamless; the copy is hidden from AT
    return ('      <div class="wall__row wall__row--%d">\n'
            '        <div class="wall__track">\n%s\n        </div>\n'
            '        <div class="wall__track" aria-hidden="true">\n%s\n        </div>\n'
            '      </div>' % (idx, body, body))

chips = '\n'.join('        <li>%s</li>' % html.escape(label(n)) for n in rest)

block = '''    <!-- WALL:START (generated by tools/build_wall.py) -->
    <section class="wall" data-theme="dark" aria-labelledby="wall-heading">
      <div class="wall__head">
        <p class="eyebrow" data-reveal>The library</p>
        <h2 id="wall-heading" class="wall__lead" data-reveal>%d homepages,<br>captured for this page.</h2>
        <p class="wall__note" data-reveal>Every one of these ships as a <code>DESIGN.md</code> spec you can point the agent at.
          Say <em>make it feel like Linear</em> and the tokens re-point, while accessibility holds.</p>
      </div>

      <div class="wall__rows">
%s
      </div>

      <div class="wall__rest" data-reveal>
        <h3>%d more that no browser can show you</h3>
        <p>Aesthetic archetypes with no address of their own, plus the handful of hosts that answer a headless
          browser with a consent wall instead of a homepage. Each still ships as a full spec.</p>
        <ul class="chips" data-reveal-group>
%s
        </ul>
      </div>
    </section>
    <!-- WALL:END -->
''' % (len(shots), '\n\n'.join(row_markup(r, i + 1) for i, r in enumerate(rows)), len(rest), chips)

src = open('index.html', encoding='utf8').read()
if 'WALL:START' in src:
    src = re.sub(r'    <!-- WALL:START.*?<!-- WALL:END -->\n', block, src, flags=re.S)
else:
    anchor = '    <!-- Gate Section -->'
    assert anchor in src, 'anchor not found'
    src = src.replace(anchor, block + '\n' + anchor)
open('index.html', 'w', encoding='utf8').write(src)
print('wall: %d screenshots, %d named-only' % (len(shots), len(rest)))
